# Generated by Django 5.2.11 on 2026-02-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0003_userprofile_bio_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('servicehub_app.userprofile',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('servicehub_app.userprofile',),
        ),
    ]
