# Generated by Django 5.2.11 on 2026-02-20 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0004_client_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='platform_commission',
            new_name='platform_fee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='provider_payout',
            new_name='provider_cut',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_fee',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
