# Generated by Django 5.2.11 on 2026-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0005_rename_platform_commission_booking_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
