# Generated by Django 5.2.11 on 2026-02-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0009_remove_booking_is_paid_to_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid_to_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
