# Generated by Django 5.2.11 on 2026-02-23 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0010_booking_is_paid_to_provider_booking_payout_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Mark as Addressed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Feedback',
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedback',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('servicehub_app.feedback',),
        ),
        migrations.CreateModel(
            name='ProviderFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Provider Feedback',
                'verbose_name_plural': 'Provider Feedback',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('servicehub_app.feedback',),
        ),
    ]
